### ISSUE TITLE
Use of Markdown is not Python 3.10-ready

### ISSUE THREAD

**Issue by nickumia-reisys** [GSA/datagov-deploy#4056]
## How to reproduce

1. Discovered in 
    - https://github.com/GSA/inventory-app/pull/505
    - https://github.com/GSA/inventory-app/actions/runs/3439015054

## Actual behavior

```bash
2022-11-10T12:33:11.39-0500 [STG/0] ERR error: subprocess-exited-with-error
   2022-11-10T12:33:11.39-0500 [STG/0] ERR
   2022-11-10T12:33:11.39-0500 [STG/0] ERR × Running setup.py install for Markdown did not run successfully.
   2022-11-10T12:33:11.39-0500 [STG/0] ERR │ exit code: 1
   2022-11-10T12:33:11.39-0500 [STG/0] ERR ╰─> [91 lines of output]
   2022-11-10T12:33:11.39-0500 [STG/0] ERR /tmp/pip-install-kk3prucd/markdown_314f12057097438f9cf263fd2ace8762/setup.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
   2022-11-10T12:33:11.39-0500 [STG/0] ERR import imp
   2022-11-10T12:33:11.39-0500 [STG/0] ERR running install
   2022-11-10T12:33:11.39-0500 [STG/0] ERR /tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
   2022-11-10T12:33:11.39-0500 [STG/0] ERR warnings.warn(
   2022-11-10T12:33:11.39-0500 [STG/0] ERR running build
   2022-11-10T12:33:11.39-0500 [STG/0] ERR running build_py
   2022-11-10T12:33:11.39-0500 [STG/0] ERR creating build
   2022-11-10T12:33:11.39-0500 [STG/0] ERR creating build/lib
   2022-11-10T12:33:11.39-0500 [STG/0] ERR creating build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/postprocessors.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/preprocessors.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/__version__.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/blockparser.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/__init__.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/util.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/blockprocessors.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/inlinepatterns.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/__main__.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/treeprocessors.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/odict.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/serializers.py -> build/lib/markdown
   2022-11-10T12:33:11.39-0500 [STG/0] ERR creating build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/smart_strong.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/smarty.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/toc.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/attr_list.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/nl2br.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/__init__.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/wikilinks.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/fenced_code.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/sane_lists.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/headerid.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/codehilite.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/tables.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/abbr.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/extra.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/def_list.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/admonition.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/meta.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying markdown/extensions/footnotes.py -> build/lib/markdown/extensions
   2022-11-10T12:33:11.39-0500 [STG/0] ERR running build_scripts
   2022-11-10T12:33:11.39-0500 [STG/0] ERR creating build/scripts-3.10
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying and adjusting bin/markdown_py -> build/scripts-3.10
   2022-11-10T12:33:11.39-0500 [STG/0] ERR changing mode of build/scripts-3.10/markdown_py from 644 to 755
   2022-11-10T12:33:11.39-0500 [STG/0] ERR running build_docs
   2022-11-10T12:33:11.39-0500 [STG/0] ERR creating build/docs
   2022-11-10T12:33:11.39-0500 [STG/0] ERR copying docs/siteindex.txt -> build/docs
   2022-11-10T12:33:11.39-0500 [STG/0] ERR Converting docs/siteindex.txt -> build/docs/siteindex.html
   2022-11-10T12:33:11.39-0500 [STG/0] ERR Traceback (most recent call last):
   2022-11-10T12:33:11.39-0500 [STG/0] ERR File "<string>", line 2, in <module>
   2022-11-10T12:33:11.39-0500 [STG/0] ERR File "<pip-setuptools-caller>", line 34, in <module>
   2022-11-10T12:33:11.39-0500 [STG/0] ERR File "/tmp/pip-install-kk3prucd/markdown_314f12057097438f9cf263fd2ace8762/setup.py", line 234, in <module>
   2022-11-10T12:33:11.39-0500 [STG/0] ERR setup(
   2022-11-10T12:33:11.39-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 177, in setup
   2022-11-10T12:33:11.39-0500 [STG/0] ERR return run_commands(dist)
   2022-11-10T12:33:11.39-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
   2022-11-10T12:33:11.39-0500 [STG/0] ERR dist.run_commands()
   2022-11-10T12:33:11.39-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
   2022-11-10T12:33:11.39-0500 [STG/0] ERR self.run_command(cmd)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR super().run_command(command)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR cmd_obj.run()
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
   2022-11-10T12:33:11.40-0500 [STG/0] ERR return orig.install.run(self)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 695, in run
   2022-11-10T12:33:11.40-0500 [STG/0] ERR self.run_command('build')
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR self.distribution.run_command(command)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR super().run_command(command)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR cmd_obj.run()
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
   2022-11-10T12:33:11.40-0500 [STG/0] ERR self.run_command(cmd_name)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 317, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR self.distribution.run_command(command)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR super().run_command(command)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/contents740207219/deps/1/python/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
   2022-11-10T12:33:11.40-0500 [STG/0] ERR cmd_obj.run()
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/pip-install-kk3prucd/markdown_314f12057097438f9cf263fd2ace8762/setup.py", line 184, in run
   2022-11-10T12:33:11.40-0500 [STG/0] ERR out = template % self._get_context(src, outfile)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/pip-install-kk3prucd/markdown_314f12057097438f9cf263fd2ace8762/setup.py", line 116, in _get_context
   2022-11-10T12:33:11.40-0500 [STG/0] ERR c['body'] = self.md.convert(src)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/pip-install-kk3prucd/markdown_314f12057097438f9cf263fd2ace8762/build/lib/markdown/__init__.py", line 375, in convert
   2022-11-10T12:33:11.40-0500 [STG/0] ERR newRoot = treeprocessor.run(root)
   2022-11-10T12:33:11.40-0500 [STG/0] ERR File "/tmp/pip-install-kk3prucd/markdown_314f12057097438f9cf263fd2ace8762/build/lib/markdown/treeprocessors.py", line 361, in run
   2022-11-10T12:33:11.40-0500 [STG/0] ERR brs = root.getiterator('br')
   2022-11-10T12:33:11.40-0500 [STG/0] ERR AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'
   2022-11-10T12:33:11.40-0500 [STG/0] ERR [end of output]
   2022-11-10T12:33:11.40-0500 [STG/0] ERR
   2022-11-10T12:33:11.40-0500 [STG/0] ERR note: This error originates from a subprocess, and is likely not a problem with pip.
   2022-11-10T12:33:11.40-0500 [STG/0] ERR error: legacy-install-failure
   2022-11-10T12:33:11.40-0500 [STG/0] ERR
   2022-11-10T12:33:11.40-0500 [STG/0] ERR × Encountered error while trying to install package.
   2022-11-10T12:33:11.40-0500 [STG/0] ERR ╰─> Markdown
   2022-11-10T12:33:11.40-0500 [STG/0] ERR
   2022-11-10T12:33:11.40-0500 [STG/0] ERR note: This is an issue with the package mentioned above, not pip.
   2022-11-10T12:33:11.40-0500 [STG/0] ERR hint: See above for output from the failure.
   2022-11-10T12:33:12.09-0500 [STG/0] OUT **ERROR** Could not install pip packages: could not run pip: exit status 1
```

## Sketch

[Notes or a checklist reflecting our understanding of the selected approach]
The problem is that Markdown deprecated some functions and something in our pipeline is still calling those deprecated functions.  So we need to just downgrade for the time being.

Related to:
- https://github.com/GSA/data.gov/issues/3876

**Comment by nickumia-reisys** [comment]
Related:
- https://stackoverflow.com/questions/64264563/attributeerror-elementtree-object-has-no-attribute-getiterator-when-trying

**Comment by nickumia-reisys** [comment]
Notes:
- I don't like that the above error doesn't get caught in our checks.  (Vendor-ing did not catch this error)
- https://docs.python.org/3.9/whatsnew/3.9.html#removed
- https://pypi.org/project/Markdown/#history

**Comment by nickumia-reisys** [comment]
This has been postponed by downgrading to Python 3.9; however, this remains an issue (as of writing).
